---

certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_hour: "5"
certbot_auto_renew_minute: "20"
certbot_auto_renew_options: "--quiet"

certbot_create_if_missing: true
certbot_create_method: standalone
certbot_testmode: true

certbot_admin_email: pr0sto@hotmail.om

certbot_create_standalone_stop_services:
  - nginx
