---

- name: Installing
  package:
    name:
      - "{{ item }}"
    state: latest
  with_items: "{{ xUsersFromGithubRequirements }}"
  tags: debug

- name: Creating group
  group:
    name: "{{ xUsersFromGithubGroup }}"
    state: present
  tags: debug

- name: Configure sudoers for group
  template:
    src: group.tpl
    dest: /etc/sudoers.d/{{ xUsersFromGithubGroup }}
    mode: 0440
    validate: 'visudo -cf %s'
  tags: debug

- uri:
    url: "https://api.github.com/repos/{{ repository }}/collaborators?affiliation=direct&permission=admin"
    headers:
      X-GitHub-Api-Version: 2022-11-28
      Accept: application/vnd.github+json
      Authorization: "Bearer {{ TOKEN }}"
  when: repository is defined and TOKEN is defined
  register: collaborators
  tags: debug

- name: Adding user
  user:
    name: "{{ item.login }}"
    shell: /bin/bash
    expires: "{{ '%s' | strftime( (ansible_date_time.epoch | int) + (86400 * (xUsersFromGithubExpire | int)) ) }}"
    groups: "{{ xUsersFromGithubGroup }}"
    append: true
  loop: "{{ collaborators.json }}"
  loop_control:
    label: "{{ item.login }}"
  when: collaborators.json is defined
  tags: debug

- name: Save authorized keys taken from GitHub
  authorized_key:
    user: "{{ item.login }}"
    state: present
    key: https://github.com/{{ item.login }}.keys
  loop: "{{ collaborators.json }}"
  loop_control:
    label: "{{ item.login }}"
  when: collaborators.json is defined
  tags: debug
