version: '3.7'

services:

  ansible:
    container_name: "ansible"
    env_file:
      - .env
    #image: ghcr.io/openworld-community/ows-events-infrastructure/ansible:latest
    image: ansible:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: ansible
    volumes:
      - ./:/etc/ansible
      - ~/.ssh/GitHub.com/pr0sto@hotmail.com.key:/root/.ssh/id_rsa:ro
    command: sh -c "ansible-galaxy install -r requirements.yml && ansible-playbook PlayBook.yml -t debug --check"

  plausible_db:
    volumes:
      - data-plausible_db:/var/lib/postgresql/data

  plausible_events_db:
    volumes:
      - data-plausible_events_db:/var/lib/clickhouse

  plausible:
    command: sh -c "sleep 10 && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    ports:
      - 8000:8000

volumes:
  data-plausible_db:
    driver: local
  data-plausible_events_db:
    driver: local
  data-plausible_geoip:
    driver: local
