#
---

- hosts: 1640081-cd84703

  tasks:

    - name: Creating project directory
      ansible.builtin.file:
        path: ~/{{ COMPOSE_PROJECT_NAME }}
        state: directory
        mode: '0755'

    - name: Copying docker compose files
      copy:
        src: ./{{ item }}
        dest: ~/{{ COMPOSE_PROJECT_NAME }}/{{ item }}
      loop:
        - docker-compose.yml
        - .env

    - name: Deploing docker compose stack
      community.docker.docker_compose:
        project_src: ~/{{ COMPOSE_PROJECT_NAME }}
        files:
          - docker-compose.yml
