name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  workflow_dispatch:


jobs:

  YAMLLint:
    name: 'YAMLLint'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.3.4

      - name: 'Installing'
        run: python -m pip install yamllint

      - name: 'Running'
        run: yamllint -c .yamllint.yml .
